#!/usr/bin/env bash

set -eu -o pipefail
shopt -s nullglob

GIT_ROOT=$(git rev-parse --show-toplevel)

function usage {
  cat <<EOF
Usage: $0 <project> [chips]
  options:"
    -h | --help       display this help
  Run the tests on the list of chips passed as arguments.
  If no chip arguments are passed, run tests on all chips.
EOF
  exit 1
}

function test_chip {
  local -r test_file=$1
  echo Running: "${GIT_ROOT}"/tools/HardwareSimulator.sh "${test_file}"
  output="$("${GIT_ROOT}"/tools/HardwareSimulator.sh "${test_file}")"
  echo "${output}"
  if ! echo "${output}" | grep -q "End of script - Comparison ended successfully"; then
    exit 1
  fi
}

while true; do
  case "$1" in
    -h | --help)
      usage
      ;;

    *) # No more options
      PROJECT=$1
      shift

      if [ $# -eq 0 ]; then
        for chip in "${GIT_ROOT}"/projects/"${PROJECT}"/*.tst; do
          test_chip "${chip}"
        done
      else
        for chip in "$@"; do
          test_chip "${GIT_ROOT}"/projects/"${PROJECT}"/"${chip}".tst
        done
      fi

      break
      ;;
  esac
done
